### ISSUE TITLE
BUG: iOS error when showing News page

### ISSUE THREAD

**Issue by penrods** [tripleblindmarket/private-kit#164] opened 2020-03-23 07:42 UTC
**News** page repeatedly gave the result below on Dazza's iPhone.  This was with version 0.5.4

He was still able to visit the page (https://privatekit.mit.edu/views) manually in his browser, and also able to follow the link to (https://privatekit.mit.edu).

Further info:
* Android phone running Play Store version was able to show the page
* Android emulator running the latest 'develo[' was also able to show the page

--------------------------

![image](https://user-images.githubusercontent.com/16079445/77292920-402d2b00-6caf-11ea-8391-0728d44339f5.png)

**Comment by rparet** [comment] 2020-03-23 13:25
Can't reproduce this with the app store build nor the current develop branch on the simulator.

**Comment by Rikku-1** [comment] 2020-03-23 20:58
I can't reproduce this either.

**Comment by rparet** [comment] 2020-03-23 21:15
Ok. Closing!

**Closed by rparet** 2020-03-23 21:15 UTC
Labels: Bug, High Priority, question
