### ISSUE TITLE
iOS build fails with yarn install

### ISSUE THREAD

**Issue by tremblerz** [tripleblindmarket/private-kit#80] opened 2020-03-17 09:32 UTC
In my setup, I required to perform `pod install` as well in order to get `npx react-native run-ios` running successfully.

Xcode 11.3.1
yarn 1.2.4
Catalina 10.15.3

Build fail log -
```
info Found Xcode workspace "PrivateKit.xcworkspace"
info Building (using "xcodebuild -workspace PrivateKit.xcworkspace -configuration Debug -scheme PrivateKit -destination id=2B640F2E-4BE8-4FEC-9D36-4B3D0E9EF7AA")
............
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening PrivateKit.xcworkspace. Run CLI with --verbose flag for more details.
note: Using new build system
note: Planning build
note: Constructing build description
error: /Users/safepath/Workspace/private-kit/ios/Pods/Target Support Files/Pods-PrivateKit/Pods-PrivateKit.debug.xcconfig: unable to open file (in target "PrivateKit" in project "PrivateKit") (in target 'PrivateKit' from project 'PrivateKit')
error: /Users/safepath/Workspace/private-kit/ios/Pods/Target Support Files/Pods-PrivateKit/Pods-PrivateKit.debug.xcconfig: unable to open file (in target "PrivateKit" in project "PrivateKit") (in target 'PrivateKit' from project 'PrivateKit')
error: /Users/safepath/Workspace/private-kit/ios/Pods/Target Support Files/Pods-PrivateKit/Pods-PrivateKit.debug.xcconfig: unable to open file (in target "PrivateKit" in project "PrivateKit") (in target 'PrivateKit' from project 'PrivateKit')
error: /Users/safepath/Workspace/private-kit/ios/Pods/Target Support Files/Pods-PrivateKit/Pods-PrivateKit.debug.xcconfig: unable to open file (in target "PrivateKit" in project "PrivateKit") (in target 'PrivateKit' from project 'PrivateKit')
error: /Users/safepath/Workspace/private-kit/ios/Pods/Target Support Files/Pods-PrivateKitTests/Pods-PrivateKitTests.debug.xcconfig: unable to open file (in target "PrivateKitTests" in project "PrivateKit") (in target 'PrivateKitTests' from project 'PrivateKit')
error: /Users/safepath/Workspace/private-kit/ios/Pods/Target Support Files/Pods-PrivateKitTests/Pods-PrivateKitTests.debug.xcconfig: unable to open file (in target "PrivateKitTests" in project "PrivateKit") (in target 'PrivateKitTests' from project 'PrivateKit')
error: /Users/safepath/Workspace/private-kit/ios/Pods/Target Support Files/Pods-PrivateKitTests/Pods-PrivateKitTests.debug.xcconfig: unable to open file (in target "PrivateKitTests" in project "PrivateKit") (in target 'PrivateKitTests' from project 'PrivateKit')
error: /Users/safepath/Workspace/private-kit/ios/Pods/Target Support Files/Pods-PrivateKitTests/Pods-PrivateKitTests.debug.xcconfig: unable to open file (in target "PrivateKitTests" in project "PrivateKit") (in target 'PrivateKitTests' from project 'PrivateKit')


** BUILD FAILED **


```

**Comment by andreanuzzo** [comment] 2020-03-17 21:01
I cannot reproduce your issues, my install works fine. 
Xcode `11.3.1`
yarn `1.22.4`
macOs `10.15.3`

One note though, other than updating `yarn`: on a different machine I had to unset the `LDFLAGS` and `CPPFLAGS` from the environment to make the `pod install` work, otherwise it would fail during the install of `glog`.

**Comment by andreanuzzo** [comment] 2020-03-17 22:47
I have tested the current build on two different macs with same macOS, yarn (1.22.4) and Xcode. One manages to compile the app, but the app is unstable when logging GPS info. 

The other reproduces your mistake and building with Xcode instead of react-native, locates the error on the missing library `@mauron85_react-native-background-geolocation`. I believe the issue is the compiler that runs beneath yarn in the different machines, but I haven't been able so far to understand what's the problem.

**Comment by harshvitra** [comment] 2020-03-17 23:28
I haven't been able to replicate this.

**Comment by tremblerz** [comment] 2020-03-17 23:45
> I have tested the current build on two different macs with same macOS, yarn (1.22.4) and Xcode. One manages to compile the app, but the app is unstable when logging GPS info.
> 
> The other reproduces your mistake and building with Xcode instead of react-native, locates the error on the missing library `@mauron85_react-native-background-geolocation`. I believe the issue is the compiler that runs beneath yarn in the different machines, but I haven't been able so far to understand what's the problem.

What is the difference between the two machines? I am able to fix the problem by running `pod install` in the ios folder, which basically installs the required dependencies.
Also what is it you found unstable in gps logging.

**Comment by andreanuzzo** [comment] 2020-03-17 23:56
One is a 2012 MBPr, the other a 2016 MBP. Same macOS and Xcode, but they have different software on it (brew vs macports, etc.). 

The 2012 builds, the 2016 does not. 

Regarding GPS logging, the 2012 was having trouble refreshing the app, went on a refresh loop. It is not happening anymore and it is running fine, so far, not sure what's changed. Please disregard the previous claim.

**Comment by andreanuzzo** [comment] 2020-03-18 14:43
Fixed build install, but does not fix GPS. 

https://github.com/andreanuzzo/private-kit/tree/andynuzzo/fix_ios_build

**Comment by rparet** [comment] 2020-03-23 21:33
Docs now say pod install and then npx so closing.

**Closed by rparet** 2020-03-23 21:33 UTC
Labels: Bug
