### ISSUE TITLE
Multilangual support not working (iOS)

### ISSUE THREAD

**Issue by andreanuzzo** [tripleblindmarket/private-kit#162] opened 2020-03-23 02:12 UTC
Version 0.5.3 (8) from Test Flight claims multilingual support. 

App does not change language on my iPhone SE, which is set onto Italian. 

Tuesday we might have to speak to Italian authorities. Can it be fixed? 

![IMG_D1CF92A73CF4-1](https://user-images.githubusercontent.com/36167533/77273315-a1da9e80-6c89-11ea-91b7-b0ca7fef6a79.jpeg)
![IMG_A7B099F62762-1](https://user-images.githubusercontent.com/36167533/77273317-a2733500-6c89-11ea-85d8-8ff5fc25a7cf.jpeg)

**Comment by tremblerz** [comment] 2020-03-23 05:50
Can you build and test? I have run Hindi version in iOS in the past.

**Comment by rparet** [comment] 2020-03-23 13:29
I've confirmed this is working on the latest version of the code. See screenshot.

@vitorpamplona this is likely due to the Apple App Store being a version (or two) behind. 


<img width="395" alt="Screenshot 2020-03-23 09 27 56" src="https://user-images.githubusercontent.com/623643/77321590-c74ac500-6ce8-11ea-9960-503c9e6bb363.png">

**Comment by rparet** [comment] 2020-03-23 18:45
Fixed by getting the right app to the app store.

**Closed by rparet** 2020-03-23 18:45 UTC
Labels: Bug, High Priority
