### ISSUE TITLE
Expanding circles on main screen not always properly centered

### ISSUE THREAD

**Issue by PMKielstra** [tripleblindmarket/private-kit#882] opened 2020-05-21 10:25 UTC
## Issue type
UI

## Version 
- Release build version: 1.0.65

## Affected Devices

| Brand        |  Model        | OS  |
| ------------ |:-------------:| ----:|
|OnePlus|OnePlus 6|Android 10 (v29)|

## Steps to reproduce
Do a clean install of Safe Paths.  Do not set up a health authority or enable location.  Close and reopen the app.  It should give the standard "You need to enable location" message.  Open and close settings.  This will clear the "You need to enable location" message, and it will look like this:

![image](https://user-images.githubusercontent.com/4313413/82549979-bd610900-9b55-11ea-83d9-a2e627ed97eb.png)

**Comment by Namit-Agrawal** [comment] 2020-05-28 20:10
I can work on this issue!

**Comment by Namit-Agrawal** [comment] 2020-05-29 04:10
I was unable to reproduce this issue on Android 10 (v29). I could not get to the screen @PMKielstra posted.

**Comment by Patrick-Erichsen** [comment] 2020-05-29 04:36
@summetj I think we can close this out. Was also unable to reproduce.

**Closed as completed** 2020-05-29 13:31 UTC
Labels: good first issue, UI/UX
